---
- name: Get current default zone
  shell: firewall-offline-cmd --get-default-zone
  register: default_zone
  changed_when: False

- name: Set default zone
  shell: firewall-offline-cmd --set-default-zone={{ shhirose_firewalld.default_zone }}
  when:
   - shhirose_firewalld.default_zone is defined
   - default_zone.stdout != shhirose_firewalld.default_zone
