---
- name: Set port
  firewalld:
    port: "{{ item.port }}"
    zone: "{{ item.zone | default(omit) }}"
    immediate: "{{ item.immediate | default(firewalld_running) }}"
    offline: "{{ item.offline | default(not firewalld_running) }}"
    permanent: "{{ item.permanent | default(False) }}"
    state: "{{ item.state }}"
  with_items: "{{ shhirose_firewalld.ports | default([]) }}"

