---
- name: Write service config file
  template:
    src: service.xml.j2
    dest: "{{ shhirose_firewalld_config_path }}/services/{{ item.name }}.xml"
  with_items: "{{ shhirose_firewalld.service_config | default([]) }}"
  notify: Reload firewalld

- name: Register service with offline firewalld
  shell: firewall-offline-cmd --new-service-from-file={{ shhirose_firewalld_config_path }}/services/{{ item.name }}.xml --name={{ item.name }}
  register: ret
  failed_when: ret.rc != 0 and ret.rc != 252
  with_items: "{{ shhirose_firewalld.service_config | default([]) }}"
  when: not firewalld_running
