---
- name: Set source permanent
  firewalld:
    source: "{{ item.source }}"
    zone: "{{ item.zone | default(public) }}"
    immediate: "{{ item.immediate | default(firewalld_running) }}"
    offline: "{{ item.offline | default(not firewalld_running) }}"
    permanent: "{{ item.permanent | default(False) }}"
    state: "{{ item.state }}"
  when: item.permanent | default(False)
  with_items: "{{ shhirose_firewalld.sources | default([]) }}"
